[package]
name = "tfc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rusb = "^0.8.1"
rust-embed = "^5.9.0"
sys-locale = "^0.1.0"
toml = "^0.5.8"
